### ISSUE TITLE
log in error email expired

### ISSUE THREAD

**Issue by cozmosnft** [tokenocean/cozmos#11]
im trying to use the las 2 emails i tried but the link is expired and im trying to create a new acc but it says that its already in use... so there's no way for me to access to the account with those 2 emails that i have used,, maybe if we don't add an expiration on the link it will resolve the issu
![error console](https://user-images.githubusercontent.com/103065410/165889648-83a0a4b5-c934-47d7-9483-2e6bef22f0cf.JPG)
![error](https://user-images.githubusercontent.com/103065410/165889650-01eef0e4-a248-4c8a-a018-760b8375a6a1.JPG)
e

**Comment by asoltys** [comment]
It's hard to remove the expiry altogether since that's not managed by our code but by a third-party authentication library we're using, but if this becomes an issue again we can always have an admin manually extend the expiry date through the database console by going to Data -> auth schema -> accounts -> Edit -> change ticket_expiry
